audit_header: false
title: Pacific Northwest Real Estate Video Blog with Armond Garcia
description: Our mission at Pacific Northwest Premier Listings is to be your best resource for Pacific Northwest real estate advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. If you are looking to buy or sell a home, you can get all the information and the latest updates, tips, and tricks from The Pacific Northwest Premier Listings, your professional Pacific Northwest Real Estate Agents.
show_custom_links: false
custom_links:
  - title:
    url:
show_custom_links_new_tab: false
custom_links_new_tab:
  - title:
    url:

client:
  name: Armond Garcia
  title:
  license_number:
  about_markdown: |
    Welcome to Northwest Premier Listings. Northwest Premier Listings is a local real estate group based in Lake Stevens to meet your needs whether buying or selling your home. By utilizing our unique industry skills, we approach every step toward those goals with honesty and integrity. Our ‘can do’ attitude will ensure you the smoothest transaction possible. We look forward to serving you.

    With over a decade of sales experience, Armond’s reputation for building sustainable relationships with his client is well regarded. Honored with the Keurig's "Spirit of Ownership Award” for outstanding customer service, he looks forward to bringing those same qualities working for you. Having lived in Snohomish County for over twenty-five years, Armond currently lives in Lake Stevens with his wife and daughters. Active in his community Armond and his family participate with the Lake Stevens Food Bank, Special Olympics, and the Brain Cancer Walk.
  brand: Pacific Northwest Premier Listings
  brokerage: Keller Williams Realty - Northsound
  market: Pacific Northwest
  address: 1906 107th Drive SE Lake Stevens WA 98258
  phone: 425-359-3856
  phone_type:
  phone2:
  phone2_type:
  email: armond@nwpremierlistings.com
  url: http://pnwpremierlistings.com

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: https://www.pnwpremierlistings.com/cma/property-valuation/
  second_CTA_text: Home Search
  second_CTA_URL: https://www.pnwpremierlistings.com/search/advanced_search/

sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: "What’s Your Pacific Northwest Home Worth?"
    CTA_text: "Are you thinking of selling your home or interested in learning about home prices in your neighborhood? We can help you."
    CTA_link_text: "Free Home Value Report"
    CTA_url: https://www.pnwpremierlistings.com/cma/property-valuation/

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/002.jpg
    CTA_title2: "Looking for a Pacific Northwest Home?"
    CTA_text2: "Search the entire MLS for your Pacific Northwest home."
    CTA_link_text2: "Search the MLS"
    CTA_url2: https://www.pnwpremierlistings.com/search/advanced_search/

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: /img/lender-headshot.jpg
  logo_path: /img/lender-logo.png
  name:
  license_number:
  company:
  company_license_number:
  phone:
  email:
  url:

socials:
  review_sm_icons: false
  facebook_url: http://facebook.com/PNWPremierListings
  linkedin_url: https://www.linkedin.com/in/armond-garcia-0a1ab37/
  youtube_url: http://youtube.com/channel/UCiQ3C0elq2XCs0KhjCdVkjw?view_as=subscriber
  twitter_url:
  instagram_url: https://www.instagram.com/armondgarciarealestate/?hl=en
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title: 'Pacific Northwest Real Estate Podcast with Armond Garcia'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the Pacific Northwest Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from Pacific Northwest Premier Listings - your professional Pacific Northwest Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in Pacific Northwest, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: 'Armond Garcia'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: Pacific Northwest Real Estate Video Blog
  hero_background_hex: '#000'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
  post_cta_image: /img/home-value.jpg
  post_cta_image2: /img/home-search.jpg

site_colors:
  brand_color: '#315c4e'
  theme_color: '#999'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: black

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#315c4e'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
